#!/bin/bash
#PBS -S /bin/bash
#PBS -o /global/scratch/rahmans/tmp/beam_analysis/col2_15cm_BS_newraster_R0.3_pi-.out
#PBS -e /global/scratch/rahmans/tmp/beam_analysis/col2_15cm_BS_newraster_R0.3_pi-.err
# Script for running sensitivity analysis
cd /home/rahmans/analysis/BeamSteeringAnalysis/plane/jsub/../
echo "Current working directory is `pwd`"
echo "Node file: $PBS_NODEFILE:"
echo "-----------------------------"
cat $PBS_NODEFILE
echo "-----------------------------"
CORES=`/bin/awk 'END {print NR}' $PBS_NODEFILE`
echo "Running on $CORES cores."
echo "Starting run at: `date`"
module load root-cern/6.14.04-gcc52
export OMP_NUM_THREADS=$CORES
python processD.py "/global/scratch/rahmans/scratch/beamStudy/beamUpstreamR0.3/col2_15cm_raster/beam_BS*" "/global/scratch/rahmans/root/beam_analysis" "col2_15cm_BS_newraster_R0.3" "pi-" 
echo "Program analysis finished with exit code $? at: `date`"
